### ISSUE TITLE
Move to a new Github org

### ISSUE THREAD

**Issue by djmitche** [json-e/json-e#430]
This package is used by more than just Taskcluster.

Let's move it to `https://github.com/json-e/json-e` where we can manage ownership independently of Mozilla.  I think that means:

 * Create the new org
 * Add ownership to some Mozilla folks
 * Transfer the repo to the new org

We'll need to do some work to point https://json-e.js.org/ to the new GH pages, but we can sort that out.

**Comment by jwhitlock** [comment]
Thanks for setting up https://github.com/json-e, @djmitche .

One issue @petemoore brought up was that the Go install package is tied to the repository URL. Does anyone have experience moving a Go package?

Looking at https://github.com/taskcluster/json-e/blob/main/RELEASING.md, I believe the others (JS, Python, Rust) can be updated by changing files after moving the repository.

**Comment by djmitche** [comment]
So, there are three possibilities for the Go package that I can think of:
 * Move it, and leave the old version behind, with a doc update
 * Maybe Go will follow the GitHub redirects that are put in place when a repo is moved?
 * We could replace the old repo with "stubs" that just import and re-export names from the latest version of the new repo.

The third option sounds attractive, but it's really no different from the first once we get beyond v4.  I can do a quick experiment to see what happens with the second option.

**Comment by djmitche** [comment]
I can confirm that go does not follow the redirects.

**Comment by djmitche** [comment]
So, here's what I think we should do:
 * Move the repo
 * Immediately fork the new location back to the old location
 * Update https://github.com/taskcluster/json-e/blob/main/jsone.go to import from the new location and update the README to contain only a note about the new location
 * Make a new patch-version tag at the old location
 * Verify that appears on pkg.go.dev
 * Update all references (links, etc.) in the new location
 * Make another patch release from the new location

I'm also a little concerned about the docs -- it looks like "personal" orgs [don't get GitHub pages anymore](https://docs.github.com/en/pages/getting-started-with-github-pages/changing-the-visibility-of-your-github-pages-site) (thanks Microsoft!) so we'll need to find some other way of hosting the docs.  That can probably be an S3 bucket.  I can set up some scripting for that.  I'm not sure that deleting the old repo and re-creating it wouldn't also disable pages, so let's not click any buttons until that scripting is done.

**Comment by djmitche** [comment]
Oh, I appear to have misunderstood that - https://json-e.github.io/_testing/ works fine.  So, I think we'll just need to make a js.org PR.

When should we do all of this?

**Comment by jwhitlock** [comment]
I think we can transfer the repository when @petemoore has a chance to weigh in on the Go options. I'm hopeful we'll start that this week.

**Comment by jwhitlock** [comment]
I talked to @petemoore, he didn't have a particular Go strategy in mind, but trusts that we can figure it out. This package doesn't appear on pkg.go.dev, so [adding there](https://go.dev/about#adding-a-package) may be a good future strategy.

@djmitche - ready to move?

**Comment by djmitche** [comment]
It does exist :)

https://pkg.go.dev/github.com/taskcluster/json-e

Let's plan to do this in the US afternoon Friday?  Do you want to ping on Matrix me around your noontime?

**Comment by jwhitlock** [comment]
* [x] Moved the repo to https://github.com/json-e/json-e
* [x] Forked back to https://github.com/taskcluster/json-e

**Comment by djmitche** [comment]
CI is up and running!

Now I just need to make a 4.4.3 release with the new location..

**Comment by djmitche** [comment]
OK, I published 4.4.3!  We're done here :)
