### ISSUE TITLE
Distribute python wheels on PyPI

### ISSUE THREAD

**Issue by bollwyvl** [json-e/json-e#443]
> thanks for json-e! :heart: 

## Elevator Pitch
It would be lovely if there were canonical `.whl` packages along with the `.tar.gz` files on PyPI.

## Use Case
My particular interest: wheels (specifically ones ending in `py3-none-any.whl`) are required for [pyodide](https://github.com/pyodide/pyodide)... and could even be used to deliver an in-browser sandbox for pure python stacks like json-e's. 

## Proposal
- where someone/somerobot is running the equivalent of `python setup.py sdist`, add `bdist_wheel`
- where someone/somerobot runs `twine upload dist/*.tar.gz` add `dist/*.whl`

## Background
Practically, recent `pip` versions will just build a wheel and install it, so it's really just pushing more work onto users' systems, and would decrease entropy and increase hashability by just a bit if done here.

More broadly, wheels are the generally-preferred format for python library distribution, as they don't require arbitrary execution at install time.

## Additional Context
Of note: wheel distributions definitely shouldn't _replace_ `sdist` distributions, as they are very handy for downstream re-packagers, as wheels often _don't_ include enough information to re-build a working package... not super relevant in this case, but just to avoid any surprises (disclaimer: maintainer on [conda-forge](https://github.com/conda-forge/json-e-feedstock/) :blush:).

**Comment by djmitche** [comment]
This sounds like something we'd be happy to do.  Any chance you want to make a PR?  Otherwise I can plan to work on this later.
