### ISSUE TITLE
Built using JSON-e: Alterschema

### ISSUE THREAD

**Issue by jviotti** [json-e/json-e#452]
In case you ever want to collect a list of projects using JSON-e in production, I recently built Alterschema (https://alterschema.sourcemeta.com), a tool to upgrade JSON Schema definitions across versions of the specification.

What is the most interesting, is that Alterschema specifies upgrades as a set of declarative transformation rules written in JSON Schema itself and JSON-e. See https://github.com/sourcemeta/alterschema/tree/master/rules.

In essence, most of the logic of the tool is just pure JSON.

Thanks a lot for JSON-e! 🙏🏻

**Comment by djmitche** [comment]
Oh, very cool!  Taskcluster uses JSON-schema pretty extensively, and ensuring version compatibility is definitely tricky.

**Comment by djmitche** [comment]
I proposed adding this to the README in https://github.com/json-e/json-e/pull/453
