### ISSUE TITLE
Questions from a potential implementor

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#475]
I was introduced to this project by @jviotti (AlterSchema author), and I must say, it's impressive.  I maintain a suite of implementations of various JSON-related technologies that are built on .Net's _System.Text.Json_ namespace, called [`json-everything`](https://github.com/gregsdennis/json-everything).

Reading through the online documentation and the issues list (both open and closed), I took [notes](https://github.com/gregsdennis/json-everything/issues/539) of things that I would need to pay particular attention to while building support for this.  Among these were some questions.

How would you like those questions?  (Just listed below, separate issues, etc.)  If someone just wanted to answer over there, that's fine for me, but I think answering some may result in updating the documentation.

**Comment by djmitche** [comment]
I'll take a pass at them over in the json-everything repo.

**Comment by djmitche** [comment]
(I'm also happy to meet with you to discuss!)

**Comment by gregsdennis** [comment]
Sounds good.  I'm also encouraged by your swift response!

**Comment by djmitche** [comment]
If you're considering a C# implementation of JSON-e, I'd very much prefer that it be in this repository, including CI to validate that it passes the tests in `specification.yml`. JSON-e isn't a "standard" and as you've noted isn't even all that clearly specified, so it's quite helpful to be able to add new cases to `specification.yml` and see how they behave across all implementations. If C# were to be the only language implementation not in this repo, it's likely it would be a "second class citizen". That said, now that none of the maintainers are actively working on JSON-e, the pace has slowed to a near-stop, so it might not be too hard to keep an external C# implementation up-to-date.

We do get a number of contributors who enjoy the challenge of implementing some relatively simple thing in a half-dozen languages. Adding another language to that mix only increases the challenge!

**Comment by djmitche** [comment]
I just peeked at bowtie. That's pretty cool! Building something similar for JSON-e would be interesting, but my gut feeling is that it's more effort, and cost for infrastructure, than is justified for the current state of the project. But, maybe I'm wrong and someone is just itching to make and deploy a cross-implementation spec validator for JSON-e!

**Comment by gregsdennis** [comment]
I think I just see things differently.

> For example, we might observe that some input currently produces an error in all in-repo implementations, and determine that it's safe to extend the language to make that input produce a result without a major version bump, but later find out that the C# implementation did not produce an error for that input.

It's the responsibility of the library maintainer to keep up with changes to the specification.  You, as the spec maintainer, don't even need to notify the library maintainer.

Furthermore, any variances between my library and any "reference implementation" (which is effectively your online playground) is reported as a bug in my library, usually by my users, and it's my responsibility to fix it.

> The downside is that making a change then requires coordinating a dozen PRs, and we risk having languages "fall behind" one another. There's also a risk of version confusion - "Go json-e@3.8 implements JSON-e 4.2 but Python json_e-3.9 implements JSON-e JSON-e 4.1"

I've never seen this to be a problem.  This kind of version lock, in my experience, is actually somewhat of a headache to maintain.

For example, my _JsonSchema.Net_ supports JSON Schema at versions 6, 7, 2019-09, 2020-12, _and_ the unpublished next version.  (I've documented that "next version" features may change without a version bump.)  However, the version of the library (SemVer) must account for both spec changes _and_ library API changes.  Most recently, I reworked how keywords are processed.  While no spec-level functionality changed, it did change my library's API and I had to bump the major version to indicate a breaking change.

Avoiding the version lock is beneficial and ideal.  Thus, my library will start at v1.0.0 (actually v0.1.0 if I publish a pre-release), and I'll document whatever JSON-e version(s) I support.

---

Thanks for the discourse.  Just so you know my background, I have over a decade of OSS experience, much of that is providing packages which implement specifications.  I'm also one of the authors on JSON Schema and a major contributor to the upcoming IETF JSON Path specification.

I think this project is really well-developed and I'd like to see it flourish.

**Comment by djmitche** [comment]
Taskcluster has used JSON-schema quite widely too, so thank you for that!

I think all of the questions are answered here?

**Comment by jviotti** [comment]
> But, maybe I'm wrong and someone is just itching to make and deploy a cross-implementation spec validator for JSON-e!

We've seen this approach to be very beneficial in JSON Schema. It might be a bit of an investment, but might help push JSON-e beyond this repo and more into an industry standard for JSON templating.

**Comment by djmitche** [comment]
That would be really cool :)

**Comment by gregsdennis** [comment]
Just wanted to mention that I've now released some interactive learning on using the _JsonE.Net_ library.

https://learn.json-everything.net/json-e  (see also some intro stuff on how the lessons work on the main page)

**Comment by djmitche** [comment]
Fantastic, thanks!
