### ISSUE TITLE
[ongoing discussion] Tests found while building an implementation

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#476]
<img width="575" alt="image" src="https://github.com/json-e/json-e/assets/2676804/591ee2bf-2bcd-4374-8716-ac4d655298c1">

Also, the documentation doesn't state this (that I could find).

**Comment by djmitche** [comment]
Good point! Do you want to make a PR to add that to `specification.yml`? The top of the "Operators" section could probably also mention this. It might also be worth mentioning that unknown operators are not allowed.

**Comment by gregsdennis** [comment]
Maybe.  For now, I'm just going to be finding missing tests 😄.

... Unless you prefer that I just list all test ideas here.

**Comment by djmitche** [comment]
Maybe one PR to add a bunch of new tests to `specification.yml` would be easiest for everyone?

**Comment by gregsdennis** [comment]
Sure.  I'll collect them as I work on my implementation and do a single PR.

**Comment by gregsdennis** [comment]
This is one of the existing tests.  I think the error message is wrong.  The parameter just needs to be an array; the items don't need to be objects.

![image](https://github.com/json-e/json-e/assets/2676804/f5b025d0-af56-4ff1-b4a7-fcde33de35e9)

**Comment by gregsdennis** [comment]
Some errors seem like they're reporting the wrong kind.  For example:

```
title: 'numeric, noninteger index'
context: {key: [1,2,3,4,5]}
template: {$eval: 'key[2.5]'}
error: 'InterpreterError: should only use integers to access arrays or strings'
```

I'd expect this to be a template error since `key[2.5]` is _never_ valid.

This is contrasted with 

```
title: 'string index'
context: {key: [1,2,3,4,5]}
template: {$eval: 'key["a"]'}
error: 'InterpreterError: should only use integers to access arrays or strings'
```

where `key["a"]` could be valid if the context is an object.

**Comment by djmitche** [comment]
In general, "TemplateError" applies to the structured data and operators, while "InterpreterError" applies to parsing strings into expressions and evaluating them. Both `key[2.5]` and `key["a"]` are strings parsed into an expression and evaluated, and both are invalid, so both generate an InterpreterError.

I don't think the distinction is particularly important to the user, but more of a historical accident of how this was implemented in JS. Maybe, in standardizing on error messages, we should drop this "kind" altogether.

**Comment by djmitche** [comment]
BTW, it would be much more searchable to include the information as text, rather than screenshots.

> This is one of the existing tests. I think the error message is wrong. The parameter just needs to be an array; the items don't need to be objects.

Agreed!

**Comment by gregsdennis** [comment]
Another thing I'm finding as I continue development is that tests are not written for feature isolation.

For example, there are no tests for `$map` over objects that don't also involve string interpolation.

These concepts should be isolated and tested separately.  Test them together also, sure, but they definitely need isolated tests.

**Comment by gregsdennis** [comment]
It also seems that you could add the examples from the docs into the test suite as some quick-win test cases.

**Comment by djmitche** [comment]
That's a good point regarding the feature isolation. It does make it difficult to bring up a new implementation!

**Comment by gregsdennis** [comment]
The tests:

```yaml
title: rstrip mixed whitspace
context: {}
template: {$eval: "rstrip(' \f\n\r\t\vabc \f\n\r\t\v')"}
result: " \f\n\r\t\vabc"
```

and

```yaml
title: lstrip mixed whitspace
context: {}
template: {$eval: "lstrip(' \f\n\r\t\vabc \f\n\r\t\v')"}
result: "abc \f\n\r\t\v"
```

might show evidence that the YAML parser being used it's working right.

The [YAML spec](https://yaml.org/spec/1.2.2/#54-line-break-characters) states

> Line breaks inside scalar content must be normalized by the YAML processor. Each such line break must be parsed into a single line feed character. The original line break format is a presentation detail and must not be used to convey content information.

This, to me, says that some of these escapes shouldn't appear in the output.

**Comment by djmitche** [comment]
I don't read that the same way you do, but at any rate, JSON-e isn't a YAML parser so I don't think this is related to JSON-e.

**Comment by djmitche** [comment]
(I commented in the linked bug)

**Comment by gregsdennis** [comment]
But all of your tests and examples are YAML, and your expression syntax supports YAML literals.  Surely you're at least _using_ a YAML parser.

**Comment by gregsdennis** [comment]
Also, this needs to be reopened.  As mentioned above, this is a continuing issue for various testing issues that I find as I'm implementing JSON-e.

**Comment by djmitche** [comment]
The tests are in YAML, but just as a convenient way to represent JSON structures.We could just as well use JSON or XML or Protobufs or whatever.

The specification is, at least for the YAML parsers we use, producing the expected JSON data structures (containing various whitespace values). My read of the JSON spec suggests all of those parsers are doing the right thing, but if they're not then that's the same bug in PyYAML, the `yaml` JS package, `serde-yaml`, and `gopkg.in/yaml`.

I forgot this was an ongoing roll-up issue, so I've re-opened it.

**Comment by gregsdennis** [comment]
> But all of your tests and examples are YAML, and your expression syntax supports YAML literals. Surely you're at least using a YAML parser.

Example:

One of your test templates is

```yaml
{$eval: '{a: {b: 13}} in ["string", 46, {a: {b: 14}}]'}
```

I'm talking about literals in strings that are to be evaluated, like `{a: {b: 13}}`.  This isn't JSON; it's YAML.  You need a YAML parser to extract this value from the string.

**Comment by djmitche** [comment]
It's true that the string you quoted is a valid YAML expression, but that's a coincidence. In general, that is an expression in the JSON-e  language. For example, in Rust it's parsed by the [`object_literal`](https://github.com/json-e/json-e/blob/main/rs/src/interpreter/parser.rs#L152) function, which expects

 * `{`
 * zero or more, comma-separated
   * a string or identifier
   * `:`
   * an expression
 * `}`

In the case of `{a: {b: 13}}`, that's parsed as `{` with one repeat, containing `a`, `:`, the expression parsed from `{b: 13}`, and `}`. That string parses as `{` with one repeat, containing `b`, `:`, the expression parsed from `13`, and `}`. `13` parses as the number 13.  The result, in Rust, is
```rust
Node::Object([
  ("a", Node::Object([
    ("b", Node::Number("13")),
  ])),
])
```

**Comment by gregsdennis** [comment]
(Just making a note)

Duplicated test:

```yaml
title:    multiplication
context:  {a: 3, b: 2}
template: {$eval: 'a * b * 3'}
result:   18
```

**Comment by gregsdennis** [comment]
Submitting a PR for additional tests.  I'm fairly certain the other impl's should pass them, but we'll see.

**Comment by gregsdennis** [comment]
@djmitche just wanted to let you know that I've put up a playground for my impl on https://json-everything.net.

**Comment by djmitche** [comment]
Very cool, thanks! We need to get some links set up from from json-e to json-everything. I'll make an issue to track that.
