### ISSUE TITLE
Document and test allowed identifiers for variables (context references) and `.` syntax

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#480]
The [docs](https://json-e.js.org/expressions.html#context-references) don't give any indication as to what's valid for the dot syntax in bar identifiers.

For example, in `x.a`, what is valid for the `a`?

In JSON Path, we've decided to limit valid identifiers to `^[a-zA-Z_][a-zA-Z0-9_]*$`.  That is, start with alpha or underscore, and the rest must be alphanumeric or underscore.

Exploring in the playground reveals this error:

```
Template: {$eval: 'b.a@4'}
Context:  {b: {'a@4': 5}}

SyntaxError: Unexpected input for 'b.a@4' at '@4'
```

What's valid for this syntax is somewhat discoverable, but it should probably be documented.

### From the tests:

```
title: invalid context
context: {'a b c': 1}
template: {}
error: 'TemplateError: top level keys of context must follow /[a-zA-Z_][a-zA-Z0-9_]*/'
panic: true
```

There aren't any tests for nested properties.

**Comment by djmitche** [comment]
In JS, at least, the right side of `.` has the same restriction as context references. But you're right that those aren't documented!
