### ISSUE TITLE
`$fromNow` odd behaviors

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#487]
Working in the playground,  I found these:

## Invalid dates accepted

This is accepted as valid, even though 31 Feb is invalid.

```yaml
{$fromNow: '1 month', from: '2017-02-31T16:27:20.974Z'}
```

(I'm not sure I can replicate this behavior.)

## Is a month just 30 days?

```yaml
{$fromNow: '1 month', from: '2017-05-01T16:27:20.974Z'}
```

evaluates to 

```yaml
'2017-05-31T16:27:20.974Z'
```

**Comment by djmitche** [comment]
We're using the underlying implementations' handling of this date format (which is one of the ISO-8601 formats, specifically the one supported by JS). I believe these agree in terms of valid dates, but may disagree for invalid dates. This particular example is rejected by Rust, Python, and Go, but accepted by JS. I'm comfortable calling this implementation-defined (in fact, EMCAScript does [exactly that](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format) - "A string containing out-of-bounds or nonconforming elements is not a valid instance of this format.").

Yes, a month is 30 days. More sophisticated date arithmetic is out-of-scope for the base language, but could be extended in with context functions for purpose-specific requirements.
