### ISSUE TITLE
Better documentation for string literals inside expression syntax

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#497]
Stemming from [this comment](https://github.com/json-e/json-e/issues/476#issuecomment-1823538182), I don't think that literals within the expression syntax are well-documented.

As the comment explains, it's technically a JSON-e expression syntax.

They look like YAML, and it's easy to assume they are.

Specifically, I think this line bolsters the misconception.

> The use of \n and \t in the example below depends on the YAML parser to expand the escapes.

Perhaps if the docs explicitly stated that these literals cannot be parsed using a JSON or YAML parser, things could be clearer.

**Comment by djmitche** [comment]
Hm, I can see how that's confusing. It's trying to clarify that JSON-e itself doesn't support `\`-escapes.

Maybe we should have a section in the beginning of the docs to help readers understand that while JSON-e operates on data structures, the only way to interact with it is through textual encodings of those data structures, typically JSON or YAML. That can get pretty confusing, as you've seen.

**Comment by djmitche** [comment]
Do you want to try to write something up along those lines?

**Comment by gregsdennis** [comment]
I don't mind contributing back to this (beyond creating an implementation and all of these reports), but I have docs of my own and a blog to write.  It's likely going to be a bit before I'd be able to work on this myself.

**Comment by djmitche** [comment]
That's fair!
