### ISSUE TITLE
Parameterless functions

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#507]
Do any of the implementations support parameterless functions?

For example, if I wanted to provide a function that generated a random number, it wouldn't need any parameters.  The template would be `{ $eval: 'rand()' }`, and I'd have to supply `rand` in my context.

Would this be accepted, or do the expression parsers expect at least one parameter?

I can't test this online because all of the built-ins have parameters, and I can't define a function in the playground (that I know of).

**Comment by djmitche** [comment]
I don't see why that wouldn't be allowed. Looking at the parser implementations in all four languages, they allow zero or more parameters.

**Comment by gregsdennis** [comment]
I'll write some local tests to verify that.  Since there aren't any built-ins, it doesn't make sense to have something in _specification.yaml_.

... unless you want to add to the `now` requirement a custom function that just returns a static value, like `foo => 42` or something...

**Comment by djmitche** [comment]
I don't think it's worth the trouble to test it in specification.yml. I'll add some unit tests. Note that Rust doesn't support custom functions at all (#508).

**Comment by gregsdennis** [comment]
Sounds good. It was just the question for me. Close if you want, or if you prefer to use it to track adding those tests, that's fine too.
