### ISSUE TITLE
WrapFunction not exported from the Go module

### ISSUE THREAD

**Issue by skapfer** [json-e/json-e#523]
It doesn't seem to be possible to inject custom functions in the context, in the Go language.

The docs claim that you can just inject bare functions https://json-e.js.org/using.html#go-golang
But the library insists on you wrapping them with `WrapFunction`
Which would be fine, but WrapFunction is only accessible internal to the Go module.

Would it be possible to make `WrapFunction` accessible outside?

**Comment by djmitche** [comment]
Yes, that sounds like a good fix. Do you want to make a PR to accomplish it?

**Comment by skapfer** [comment]
> Yes, that sounds like a good fix. Do you want to make a PR to accomplish it?

Done: https://github.com/json-e/json-e/pull/524
