### ISSUE TITLE
new $reduce op raises a new error with odd format

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#538]
One of the tests for the new `$reduce` operation raises an error regarding property count:

> TemplateError: $reduce must have exactly three properties

1. None of the other operators throws an error mentioning property count.
2. The way the property count is expressed is not ideal.

First, I'm not against having a new error message, but there should be consistency.  For example:

```
Title:    $eval with undefined properties
Template: {"$eval":"13","wrong":"a + b"}
Context:  {}
Error:    "TemplateError: $eval has undefined properties: wrong"
```

or

```
Title:    let without in
Template: {"$let":{"x":1,"y":2}}
Context:  {}
Error:    "TemplateError: $let operator requires an `in` clause"
```

I think the error should fit into one of these.

However, if we want to stay with this message, I recommend using the numeral "3" instead of the word "three".  I use error message templates to facilitate code re-use, and translating from the number type in to its corresponding English word is not a trivial task and would require me to pull in a new dependency for a general solution (which seems odd for just this).

Again, my preference is that the error message matches the ones that are already issued by the other operators.

Ref: https://github.com/json-everything/json-everything/pull/805

**Comment by djmitche** [comment]
Error messages aren't covered by semver, so I think it's fine to fix this post-release.

What message would you prefer? Would you like to make a PR?

**Comment by gregsdennis** [comment]
> What message would you prefer?

It should match the existing messages as I've listed above. 

Call out extra and missing properties, like the other operators.

**Comment by gregsdennis** [comment]
Looking at the other code, it does appear that the `$map` and `$find` oeprators also use this style of error.  I can probably just hack something in.

**Comment by gregsdennis** [comment]
JsonE.Net now supports `$reduce` and `range()`
