### ISSUE TITLE
$let statement not updating context in python

### ISSUE THREAD

**Issue by bhearsum** [json-e/json-e#545]
For example:
```
~/tmp/2024-11-28 ❯ cat test.py                                                                                                                                                              
import jsone
import pprint

yaml = """
foo:
    - $let:
        test: "somestring"
      in:
        deep: 'test string: ${test}'
"""
context = {}
pprint.pprint(jsone.render(yaml, context))
```

This seems to work fine in the playground:
![clipboard](https://github.com/user-attachments/assets/152b301c-7562-4bc7-915c-eac6ff8cb282)

**Comment by djmitche** [comment]
Ah, I see it now! In chat, Matrix's rendering was stripping the leading whitespace so I wondered if this was a whitespace issue. Which distracted me from seeing that nothing ever parses the YAML into a data structure. So you're just rendering the string.

![image](https://github.com/user-attachments/assets/de337d95-15ba-4054-b037-526764f045c4)

**Comment by bhearsum** [comment]
Indeed! Strings are not yaml...so these tests were not equivalent. Passing the object as a dict fixes the issue.
